export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";

export const SET_CART = "SET_CART";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_SIMILAR_PRODUCTS = "SET_SIMILAR_PRODUCTS";

export const SET_CURRENT_ROUTE="SET_CURRENT_ROUTE"
export const SET_PREV_ROUTE="SET_PREV_ROUTE"